"""Documentation skill - auto-generate docs for a project."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

from app.skills.base import BaseSkill, SkillResult
from app.integrations.ollama.client import OllamaClient
from app.config.settings import settings


class DocumentationSkill(BaseSkill):
    name = "documentation"
    version = "1.0.0"
    description = "Generate documentation (docstrings and README) for Python modules."
    required_tools = ["read_file", "write_file", "extract_docstrings", "generate_markdown_doc"]

    def __init__(self, tools: Dict, ollama: OllamaClient, model: str = "") -> None:
        super().__init__(tools)
        self.ollama = ollama
        self.model = model or settings.OLLAMA_DEFAULT_MODEL

    async def execute(
        self,
        path: str,
        output_dir: Optional[str] = None,
        generate_readme: bool = True,
    ) -> SkillResult:
        p = Path(path)
        if p.is_file():
            files = [path]
        else:
            files = [str(f) for f in p.rglob("*.py") if not f.name.startswith("test_")]

        output_dir = output_dir or str(p / "docs")
        doc_tool = self._get_tool("generate_markdown_doc")

        generated = []
        tool_calls = 0
        for source in files[:20]:  # Limit to 20 files
            src_path = Path(source)
            doc_out = str(Path(output_dir) / f"{src_path.stem}.md")
            result = await doc_tool.run(source_path=source, output_path=doc_out)
            tool_calls += 1
            if result.success:
                generated.append(doc_out)

        readme_content = ""
        if generate_readme and generated:
            project_name = p.name if p.is_dir() else p.stem
            summaries = "\n".join(f"- {g}" for g in generated[:10])
            prompt = f"""Project: {project_name}
Generated documentation for these modules:
{summaries}

Write a concise README.md introduction paragraph (2-3 sentences) for this project."""
            try:
                readme_content = await self.ollama.generate_with_retry(
                    model=self.model,
                    prompt=prompt,
                    options={"temperature": 0.3, "num_predict": 300},
                )
            except Exception:
                readme_content = f"# {project_name}\n\nDocumentation generated by AAOS.\n"

            write_tool = self._get_tool("write_file")
            readme_path = str(Path(output_dir) / "README.md")
            await write_tool.run(path=readme_path, content=readme_content)
            tool_calls += 1
            generated.append(readme_path)

        return SkillResult(
            success=True,
            output=generated,
            tool_calls_made=tool_calls,
            metadata={"files_documented": len(generated), "output_dir": output_dir},
        )
